name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /github/workspace

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Use a Ruby version that meets your gemspec requirements

      - name: Install dependencies
        run: bundle install
        # If your Gemfile is not in the root, add working-directory: ./docs (or your path)

      - name: Build site
        run: bundle exec jekyll build
        # Adjust working-directory if needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site  # or the folder where your built site is located
